/**
 * {
 "_id": "59f1e49a9bfd8f3bd030eed7",
 "title": "轻薄本",
 "status": 1,
 "pic": "public\\upload\\HYWKHxrKgE9O6zKajRTmb50B.png",
 "pid": "59f1e1ada1da8b15d42234e9",
 "sort": 100,
 "is_best": 1,
 "go_product": 1,
 "product_id": "59f1e49a9bfd8f3bd030eed7"
 }
 */

export class CategoryData {
  _id: string
  title: string
  status: number
  pic: string
  pid: string
  sort: number
  is_best: number
  go_product: number
  product_id: string
}