/**
 * {
 "_id": "6332bc60a3a7080ac06eaee8",
 "title": "小米12s",
 "cid": "59f1e4919bfd8f3bd030eed6",
 "price": 2999,
 "pic": "public\\upload\\5xyr9OTSK1pwJ5ng7YgpKOkd.png",
 "sub_title": "下单立减100",
 "s_pic": "public\\upload\\5xyr9OTSK1pwJ5ng7YgpKOkd.png_200x200.png"
 }
 */
export class GoodData {
  _id: string
  title: string
  cid: string
  price: number
  pic: string
  sub_title: string
  s_pic: string
}